In [2]:
## using libraries tensorflow in keras
!pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [5]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [6]:
## tensorflow > 2.0
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [8]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
## initialise vocab size
voc_size=10000

In [10]:
## to convert to OHE representation- it fetches the index of words ( from sent ) lying at index in vocabulary

onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[6060, 908, 5247, 3547], [6060, 908, 5247, 8495], [6060, 8174, 5247, 2302], [1562, 6014, 5082, 4334, 5278], [1562, 6014, 5082, 4334, 4845], [7071, 6060, 3252, 5247, 9815], [2158, 1094, 6864, 4334]]


In [2]:
## word embedding representation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [22]:
## since length of above sentences vary, in order to train the model , we need to have them in same size so for padding we assume the sent length as 8, pad_swequence will make all sent of length 8 using 0,0,0s
## so now input size is fixed
## for post padding - 0s are added in end
## if we take higher sent length = out of vocab issue can be avoided ; semantic meaning can be restored

## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6060  908 5247 3547]
 [   0    0    0    0 6060  908 5247 8495]
 [   0    0    0    0 6060 8174 5247 2302]
 [   0    0    0 1562 6014 5082 4334 5278]
 [   0    0    0 1562 6014 5082 4334 4845]
 [   0    0    0 7071 6060 3252 5247 9815]
 [   0    0    0    0 2158 1094 6864 4334]]


In [14]:
## 10 feature dimesnions- everuy word is represented by 10 features, if we have huge data set; we use dim=500
dim=10

In [15]:
## we will make a sequential model, after that we will below params to enbedding layer - voc_size; feature size, sent lengths
##

model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
##'the glass of milk'= vector of sent 1
embedded_docs[0]

array([   0,    0,    0,    0, 6060,  908, 5247, 3547], dtype=int32)

In [18]:
## each value of above array is represented by 10 features
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 141ms/step


array([[ 0.04983083,  0.02599504, -0.02120192, -0.04675944,  0.02521599,
        -0.00745797,  0.01822691, -0.04080933, -0.04012754, -0.02952853],
       [ 0.04983083,  0.02599504, -0.02120192, -0.04675944,  0.02521599,
        -0.00745797,  0.01822691, -0.04080933, -0.04012754, -0.02952853],
       [ 0.04983083,  0.02599504, -0.02120192, -0.04675944,  0.02521599,
        -0.00745797,  0.01822691, -0.04080933, -0.04012754, -0.02952853],
       [ 0.04983083,  0.02599504, -0.02120192, -0.04675944,  0.02521599,
        -0.00745797,  0.01822691, -0.04080933, -0.04012754, -0.02952853],
       [-0.00359077, -0.02939084,  0.03108886,  0.04770554, -0.04181021,
        -0.04114711, -0.02472973,  0.00406317,  0.0401299 , -0.04588256],
       [ 0.00115812,  0.01611612, -0.00490562, -0.01301813, -0.02049974,
        -0.0385257 ,  0.0383878 ,  0.03551027, -0.04663881, -0.03728242],
       [ 0.0320443 , -0.0186682 ,  0.00590358, -0.00282828, -0.02486416,
         0.0060506 , -0.02765554,  0.01047004

In [19]:
# 10 feature value of all sent
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 48ms/step
[[[ 0.04983083  0.02599504 -0.02120192 -0.04675944  0.02521599
   -0.00745797  0.01822691 -0.04080933 -0.04012754 -0.02952853]
  [ 0.04983083  0.02599504 -0.02120192 -0.04675944  0.02521599
   -0.00745797  0.01822691 -0.04080933 -0.04012754 -0.02952853]
  [ 0.04983083  0.02599504 -0.02120192 -0.04675944  0.02521599
   -0.00745797  0.01822691 -0.04080933 -0.04012754 -0.02952853]
  [ 0.04983083  0.02599504 -0.02120192 -0.04675944  0.02521599
   -0.00745797  0.01822691 -0.04080933 -0.04012754 -0.02952853]
  [-0.00359077 -0.02939084  0.03108886  0.04770554 -0.04181021
   -0.04114711 -0.02472973  0.00406317  0.0401299  -0.04588256]
  [ 0.00115812  0.01611612 -0.00490562 -0.01301813 -0.02049974
   -0.0385257   0.0383878   0.03551027 -0.04663881 -0.03728242]
  [ 0.0320443  -0.0186682   0.00590358 -0.00282828 -0.02486416
    0.0060506  -0.02765554  0.01047004 -0.02827717 -0.01791488]
  [-0.00914551 -0.01739172  0.04351762  0.04617849  0.03085

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 6060,  908, 5247, 3547], dtype=int32)

In [21]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 16ms/step
[[ 0.04983083  0.02599504 -0.02120192 -0.04675944  0.02521599 -0.00745797
   0.01822691 -0.04080933 -0.04012754 -0.02952853]
 [ 0.04983083  0.02599504 -0.02120192 -0.04675944  0.02521599 -0.00745797
   0.01822691 -0.04080933 -0.04012754 -0.02952853]
 [ 0.04983083  0.02599504 -0.02120192 -0.04675944  0.02521599 -0.00745797
   0.01822691 -0.04080933 -0.04012754 -0.02952853]
 [ 0.04983083  0.02599504 -0.02120192 -0.04675944  0.02521599 -0.00745797
   0.01822691 -0.04080933 -0.04012754 -0.02952853]
 [-0.00359077 -0.02939084  0.03108886  0.04770554 -0.04181021 -0.04114711
  -0.02472973  0.00406317  0.0401299  -0.04588256]
 [ 0.00115812  0.01611612 -0.00490562 -0.01301813 -0.02049974 -0.0385257
   0.0383878   0.03551027 -0.04663881 -0.03728242]
 [ 0.0320443  -0.0186682   0.00590358 -0.00282828 -0.02486416  0.0060506
  -0.02765554  0.01047004 -0.02827717 -0.01791488]
 [-0.00914551 -0.01739172  0.04351762  0.04617849  0.03085183 -0.02190039
 